Session/7の実装
r-arahata/iOS-practice pull request #8
Opened 2023-07-18 08:37 UTC by r-arahata

Codableの仕組みを利用して、YumemiWeatherのAPIのパラメータを作成
Codableの仕組みを利用して、YumemiWeatherのAPIの結果を扱うように実装

2023-07-18 09:08 UTC, AQ-RyukiTani requested changes

2023-07-18 09:08 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +struct WeatherInfo: Codable {
ここのリクエストとレスポンスのstructは別ファイルに定義しよう。
それと命名もわかりやすい名前に修正しよう

2023-07-18 09:08 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            let weatherInfoEncode = WeatherInfoEncode(area: "Tokyo", date: "2020-04-01T12:00:00+09:00")
dateは今日の日付が入るように修正しよう！

2023-07-18 09:08 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            encoder.outputFormatting = [.prettyPrinted, .withoutEscapingSlashes]
この二つのプロパティはどういう理由でつけた？

2023-07-18 09:08 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            let jsonWeatherInfo = try YumemiWeather.fetchWeather(jsonString!)
基本的に`!`は使用したくないからjsonStringはnullSaferyにしよう！

2023-07-19 02:04 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            encoder.outputFormatting = [.prettyPrinted, .withoutEscapingSlashes]
参考にしたサイトにこのように書いており、jsonの文字列の可読性が上がるなら良いと思ってつけました。

2023-07-19 02:36 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +struct WeatherInfo: Codable {
[APIに関するリクエストとレスポンスのstructを新しいファイルに定義](https://github.com/r-arahata/iOS-practice/pull/8/commits/23509464c3a4f50ffe52b792ececbe3e6cafa8e0)

2023-07-19 02:39 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            let weatherInfoEncode = WeatherInfoEncode(area: "Tokyo", date: "2020-04-01T12:00:00+09:00")
[APIにリクエストする際のdateを現在の日付に変更](https://github.com/r-arahata/iOS-practice/pull/8/commits/d0eabcf0e5be5a9e5a2a74a4c23f157bbcc2ed2b)

2023-07-19 02:39 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            let jsonWeatherInfo = try YumemiWeather.fetchWeather(jsonString!)
[try YumemiWeather.fetchWeather(jsonString!)の!を避けるようにデフォルトのデータを作成](https://github.com/r-arahata/iOS-practice/pull/8/commits/98d1b8ecc89205806ad4690665929ce1276fc924)

2023-07-19 02:50 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            let jsonWeatherInfo = try YumemiWeather.fetchWeather(jsonString!)
nullSaferyというのはオプショナル型にするということで合っていますか。
また、この書き方は合っていませんか。

<img width="740" alt="スクリーンショット 2023-07-19 11 44 54" src="https://github.com/r-arahata/iOS-practice/assets/122420780/d3614ec9-98c5-4a7a-8691-60b723a511a6">

2023-07-19 02:50 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            let jsonWeatherInfo = try YumemiWeather.fetchWeather(jsonString!)
！を避けるために別の方法を書いてみました。

[try YumemiWeather.fetchWeather(jsonString!)の!を避けるようにデフォルトのデータを作成](https://github.com/r-arahata/iOS-practice/pull/8/commits/98d1b8ecc89205806ad4690665929ce1276fc924)

2023-07-19 04:35 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +struct WeatherInfo: Codable {
リクエストとレスポンスはそれぞれファイル分けてほしい！
それとstructの命名が良くないかな、JsonResponseDataだと何が入っている構造体なのかわからない！

2023-07-19 04:38 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            encoder.outputFormatting = [.prettyPrinted, .withoutEscapingSlashes]
なるほどね！
このJsonを出力するんだったら全然良いんだけど、今回はjson文字列をAPIに渡すだけだから不要な処理を入れていることになるからいらないと思う！

2023-07-19 04:45 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            let jsonWeatherInfo = try YumemiWeather.fetchWeather(jsonString!)
nullSaferyってのはnullの場合`!`で強制アンラップするとクラッシュするからnullの可能性がある変数はオプショナルバインディングしようって話！
オプショナルバインディングについて調べてみて！

2023-07-19 06:17 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +struct WeatherInfo: Codable {
[WeatherAPIDataファイルの削除](https://github.com/r-arahata/iOS-practice/pull/8/commits/2addef008f204217cfba75bbc24d3419315afed7)
[APIにリクエストを送る際のstructを定義](https://github.com/r-arahata/iOS-practice/pull/8/commits/bb8d3b14eddbc7fadeb37d74c3ce56a051b88535) 
[APIからレスポンスを受け取る際のStructファイルを定義](https://github.com/r-arahata/iOS-practice/pull/8/commits/6c4e91362236de04d235b580516df7d335fc74ba)
[APIにリクエストを送る際のstructの名前をJsonRequestDataからWeatherInfoRequestに変更](https://github.com/r-arahata/iOS-practice/pull/8/commits/53bf5fa7cb5dd02baa8c4b39a81763dc4df4ee91)
[APIからリクエストを受け取る際のstructの名前をJsonResponseDataからWeatherInfoResponseに変更](https://github.com/r-arahata/iOS-practice/pull/8/commits/c4d1a547b858d978491ff56dd5767335486642b3)

2023-07-19 06:17 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            encoder.outputFormatting = [.prettyPrinted, .withoutEscapingSlashes]
[jsonデータを見やすくする処理を削除](https://github.com/r-arahata/iOS-practice/pull/8/commits/f2a9d6c0b2497f309de8c5ce91f3fc0f44775d8d)

2023-07-19 06:18 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            let jsonWeatherInfo = try YumemiWeather.fetchWeather(jsonString!)
[jsonStringがnilの際、デフォルト値を使うのをやめてエラーを出すように変更](https://github.com/r-arahata/iOS-practice/pull/8/commits/304639cad7e949bc7b0187ed652c46df975e5dba)
[jsonWeatherInfo.data(using: .utf8)!の！を避けるために、オプショナルバインディングを使用](https://github.com/r-arahata/iOS-practice/pull/8/commits/a0e5038ffe255bce7e2bb065db87987470f2aa14)

2023-07-19 09:53 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            if let jsonData = jsonData {
こういう場合はif文じゃなくてguard文使って早期リターンしよう！

2023-07-19 09:54 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            if let jsonString = jsonString {
こういう場合はif文じゃなくてguard文使って早期リターンしよう！

2023-07-20 01:23 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            if let jsonData = jsonData {
if letはguardとやっていることは同じだと思っているのですが、早期リターンするguardの方がよく使われるのですか。

2023-07-20 01:33 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            if let jsonString = jsonString {
[APIからjsonデータを取得する処理のif文をguard文に変更](https://github.com/r-arahata/iOS-practice/pull/8/commits/b37b23dfb0912b0c27ec6b4df8793ef8c2655da5)

2023-07-20 01:33 UTC, r-arahata commented on iOS-practice/WeatherAPIService.swift
> +            if let jsonData = jsonData {
[デコードする際の処理のlet文をguard文にへんこう](https://github.com/r-arahata/iOS-practice/pull/8/commits/67102535180b9dd9ebc9afcb35b0e40af49df4f8)

2023-07-20 04:07 UTC, AQ-RyukiTani commented on iOS-practice/WeatherAPIService.swift
> +            if let jsonData = jsonData {
やってることは同じだけどif文使ったらコード文長くなるから可読性が低くなる
`guard let jsonData = jsonData else { return }`って書いたらわかりやすいよね！

2023-07-20 04:09 UTC, AQ-RyukiTani approved these changes

2023-07-20 04:11 UTC, AQ-RyukiTani commented
動作確認を貼ってほしい！

2023-07-20 05:18 UTC, r-arahata commented
動作確認の動画です。
https://github.com/r-arahata/iOS-practice/assets/122420780/f82e6f8b-a7dc-44d1-ac4c-ee30c87b39c2

2023-07-20 05:33 UTC, AQ-RyukiTani approved these changes

2023-07-20 05:33 UTC, merged